### ISSUE TITLE
Balancing

### ISSUE THREAD

**Issue by MufidJamaluddin** [A2JTK16/Travlendar#4]
Dalam pengerjaan proyek ini, menurut saya ada yang kurang balance. Apakah ini hanya perasaan saya?

MockUp Karya Faiz itu sangat bagus, mari kita lihat apa yang terjadi jika MockUp tersebut direalisasikan.

Perjalanan Pertama
- Intial Location : Kosan 
- Event : Kuliah di Polban
- Event Location : Polban

Perjalanan Kedua
- Initial Location : Rumah
- Event : Mancing
- Event Location : Kolam Ikan

Dilihat dari sisi sosial, itu semua event berhubungan. tetapi apakah menurut sistem komputer,
yang kaku, TRUE or FALSE, itu event berhubungan? tentu tidak.

Konsep berhubungan menurut komputer gini :

Event Pertama
- ID Event : 1
- Event : Kuliah di Polban
- Event Loc : Polban

Event Kedua
- ID Event : 2
- Event : Mancing
- Event Loc : Kolam Ikan

Perjalanan
-  ID Event 1
- ID Event 2

Terlihat Event 1 dan Event 2 dihubungkan oleh Perjalanan. Ada cara lain menghubungkannya, yaitu sistem (back-end) yang menghubungkannya, query database, atau database entity.

Hubungan tersebut biasanya direpresentasikan oleh garis.

**Comment by nmuntaaza** [comment]
@MufidJamaluddin Saya rasa ada kesalahpahaman mufid

**Comment by MufidJamaluddin** [comment]
Mohon penjelasannya tentang perbedaan kedua diagram ini

![flow studi kasus v3-fix](https://user-images.githubusercontent.com/28973632/31715400-eecaa882-b42d-11e7-8284-adb04ce61969.jpg)

![h add new event](https://user-images.githubusercontent.com/28973632/31715447-1a1d9058-b42e-11e7-8d67-584088d8d43d.png)

**Comment by MaulanaIbrahim** [comment]
kalau menurut maul untuk yang intial location itu di awal di isi oleh user kemudian untuk event selanjutnya initial location di isi lokasi akhir event pertama . begitu seterusnya
